[build-system]
requires=["setuptools>=61.0"]
build-backend="setuptools.build_meta"

[project]
name="Arabic Legal Document QA"
version="0.1.0"
description="System answers legal questions"
readme="README.md"
requires-python -">=3.10,<3.14"

authors=[
    {name="Manar Saber"}
]

dependencies=[
    "fastapi",
    "dvc-gdrive"
]

[project.optional-dependencies]

dev=[
    "pytest"
]

test = [
    "pytest",
    "pytest-cov",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.ruff.format]
quote-style = "double"
